<HEAD>
<TITLE>Apple Registration - photokina 2006</TITLE>
<!-- BEGIN META TAG INFO -->
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<META http-equiv=pics-label content='(pics-1.1 "http://www.icra.org/ratingsv02.html" l gen true for "http://www.apple.com" r (cz 1 lz 1 nz 1 oz 1 vz 1) "http://www.rsac.org/ratingsv01.html" l gen true for "http://www.apple.com" r (n 0 s 0 v 0 l 0))'>
<META http-equiv=Expires content="Fri, 26 Mar 1999 23:59:59 GMT">
<META content="Apple Computer, Inc." name=Author><LINK href="http://www.apple.com/" rel=home>
<LINK href="http://www.apple.com/find/sitemap.html" rel=index>
<LINK media=all href="includes/global.css" type=text/css rel=stylesheet>
<LINK media=all href="includes/pro.css" type=text/css rel=stylesheet>
<LINK media=print href="includes/globalprint.css" type=text/css rel=stylesheet>
<META content="MSHTML 6.00.2800.1400" name=GENERATOR>
</HEAD>